## 1.)

### a.)

In [1]:


# v_p = r / t_p 

## 2.)

In [2]:
import numpy as np
M = np.array([
    [-1.8 , -0.38, -0.96],
    [-0.38, -1.9 , 0.62 ],
    [-0.96,  0.62, 3.7  ]
]) * 10**17

### a.)

In [3]:
M_0 = 1/np.sqrt(2) * np.sqrt(sum(M.flatten()**2))
print(f'M0 = {M_0}')

M_W = (2/3) * (np.log10(M_0) - 9.1)
print(f'MW = {M_W}')

M0 = 3.42350697385006e+17
MW = 5.622980811255467


### b.)

In [4]:
from numpy.linalg import eig

In [5]:
eig_val, eig_vec = np.linalg.eig(M)
print(eig_val)

[ 3.94087273e+17 -2.23977183e+17 -1.70110090e+17]


In [6]:
eig_vals = np.array([eig_val[0], eig_val[2], eig_val[1]])
eig_vals

array([ 3.94087273e+17, -1.70110090e+17, -2.23977183e+17])

In [12]:
m_princ = np.array(
    [
        [eig_vals[0], 0, 0],
        [0, eig_vals[1], 0],
        [0, 0, eig_vals[2]]
    ]
)

In [13]:
m_princ

array([[ 3.94087273e+17,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.70110090e+17,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -2.23977183e+17]])

### c.)

In [9]:
eps = np.round(eig_vals[1] / abs(eig_vals[0]), 2)
print(f'Epsilon = {eps},  pure compensated linear vector dipole source expected')

Epsilon = -0.43,  pure compensated linear vector dipole source expected


### d.)

In [10]:
M_dc = np.array(
    [
        [(1/2)*(eig_vals[0] - eig_vals[2]), 0, 0],
        [0, 0, 0],
        [0, 0, (-1/2)*(eig_vals[0] - eig_vals[2])]
    ]
)

M_clvd = np.array(
    [
        [-eig_vals[1] / 2, 0, 0],
        [0, eig_vals[1], 0],
        [0, 0, -eig_vals[1] / 2]
    ]
)

print(M_dc)
print('')
print(M_clvd)

[[ 3.09032228e+17  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.09032228e+17]]

[[ 8.5055045e+16  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00 -1.7011009e+17  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  8.5055045e+16]]


In [11]:
M_dc_scalar = 1/np.sqrt(2) * np.sqrt(sum(M_dc.flatten()**2))
M_clvd_scalar = 1/np.sqrt(2) * np.sqrt(sum(M_clvd.flatten()**2))

print(M_dc_scalar)
print(M_clvd_scalar)

3.0903222806802886e+17
1.4731965929674778e+17


### e.)